version: '3.8'

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "4444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: