version: '3.8'

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: Users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
    ports:
      - "4444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: